#给应用起一个名字
spring:
  application:
    name: product
  #配置数据库地址
  datasource:
    driver-class-name: com.mysql
#给他配上eureka的地址
eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
